name: Deploy to cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Install SSH key
      #   run: |
      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
      #     echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
      #     ssh-keyscan -t rsa ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      # - name: Connect and deploy using rsync
      #   run: |
      #     # rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete dist/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "ls -la"

      # - name: Remove SSH key
      #   if: always()
      #   run: rm ~/.ssh/id_rsa
      # DEBUG
      - name: Debug
        run: |
          echo ${{ secrets.REMOTE_HOST }}
          echo ${{ secrets.REMOTE_USER }}
          echo ${{ secrets.SSH_PRIV_KEY }}
          # echo the length of each
          echo Remote host length:
          echo ${{ secrets.REMOTE_HOST }} | wc -c

          echo Remote user length:
          echo ${{ secrets.REMOTE_USER }} | wc -c

          echo SSH key length:
          echo ${{ secrets.SSH_PRIV_KEY }} | wc -c

      - name: Testing the deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIV_KEY }}

          script: |
            ls -la
            echo "Nice! Deployment was successful!"
